export { default as Menu } from './menu'
export { default as Users } from './users'
export { default as Apps } from './apps'
export { default as Contact } from './contact'
export { default as About } from './about'
export { default as Ventures } from './ventures'
export { default as Player } from './player'
export { default as Newsletters } from './newsletters'
